name = "doverdesign"
compatibility_date = "2026-02-15"

[[d1_databases]]
binding = "DB"
database_name = "coastal-alchemy"
database_id = "2f9d4610-5d69-43f6-a133-08bba5fa2d75"
preview_database_id = "2f9d4610-5d69-43f6-a133-08bba5fa2d75"
migrations_dir = "db/migrations"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "coastal-alchemy"
preview_bucket_name = "coastal-alchemy"
